# build and push builded images
- hosts: newvm
  become: true
  vars_files:
    - "secrets/docker_hub.yml"

  roles:
   # - role: install-package-debian
   #     when: ansible_facts['os_family'] == 'Debian'

   # - role: install-package-centos
   #     when: ansible_facts['os_family'] == 'CentOS'
    - install-package
    - install-docker
    - administration-env
    - login-docker
    - build-images
    - docker-deploy
